name: notify-reviewers

on:
  workflow_call:
    inputs:
      pr_url:
        required: true
        type: string
      reviewers:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Reviewers
        run: |
          echo "Reviewers to notify: ${{ inputs.reviewers }}"
          
      - name: Verify Environment
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Error: DISCORD_WEBHOOK_URL is not set"
            exit 1
          fi
          if [ -z "$REVIEWER_MAP" ]; then
            echo "Error: REVIEWER_MAP is not set"
            exit 1
          fi
          echo "✓ All required environment variables are set"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REVIEWER_MAP: ${{ secrets.REVIEWER_DISCORD_MAP }}

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REVIEWER_MAP: ${{ secrets.REVIEWER_DISCORD_MAP }}
        run: |
          reviewers="${{ inputs.reviewers }}"
          message=""
          
          # Split reviewers by space and process each
          for user in $reviewers; do
            # Trim any whitespace from username
            user=$(echo "$user" | xargs)
            if [ -n "$user" ]; then
              discord_id=$(echo "$REVIEWER_MAP" | jq -r --arg user "$user" '.[$user]')
              if [[ "$discord_id" != "null" ]]; then
                message+="<@$discord_id> "
              fi
            fi
          done

          if [[ -n "$message" ]]; then
            # Construct and send the message
            json_payload=$(jq -n \
              --arg content "$message Please review the PR: ${{ inputs.pr_url }}" \
              '{content: $content}')
            
            curl -X POST "$DISCORD_WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d "$json_payload"
          else
            echo "No valid Discord IDs found for the given reviewers"
          fi
